### ISSUE TITLE
Cannot install from a local path using `kim-api-v2-collections-management`

### ISSUE THREAD

**Issue by meTchaikovsky** [openkim/kim-api#19]
Hi!
I want to install from a local path by using the command 
`kim-api-v2-collections-management install user ./amp_model_driver`
but I failed with an error:

    *** ERROR *** Unable to successfully contact openkim.org to check ./amp_parameterized_model compatibility.

    Aborting!

I'm actually following the instructions given in `amp` documentation [https://amp.readthedocs.io/en/latest/moleculardynamics.html](url). In the step of "Installation of amp_model_driver", I need to use `kim-api-v2-collections-management` to install from a local path.

How can this be fixed?

**Comment by dskarls** [comment]
What version of `wget` are you using?  This is probably an SSL protocol version issue.

**Comment by meTchaikovsky** [comment]
> What version of `wget` are you using? This is probably an SSL protocol version issue.

It is `GNU Wget 1.20 built on darwin18.2.0` I'm using.

**Comment by ellio167** [comment]
Hi, I'm actually a bit confused by the command line and error you posted:

`kim-api-v2-collections-management install user ./amp_model_driver`
but I failed with an error:

```
*** ERROR *** Unable to successfully contact openkim.org to check ./amp_parameterized_model compatibility.

Aborting!
```
The command line lists `./amp_model_driver`, but the error message lists `./amp_parameterized_model`

My guess is that you need to first install the model driver and then the model.  Otherwise (if you try to install the model first) the command will try to find the model driver at openkim.org, and for some reason on your machine the command is not able to access the website and, thus, fails.

So, try the following commands, in order, and see if it works:

`kim-api-v2-collections-management install user ./amp_model_driver`
`kim-api-v2-collections-management install user ./amp_parameterized_model`
