### ISSUE TITLE
Passing particle charge from LAMMPS into OpenKIM

### ISSUE THREAD

**Issue by adityakavalur** [openkim/kim-api#86]
Hi

I have been testing out OpenKIM recently and its a really useful project, glad to see the awesome progress you all are making!

As for my scope, I am looking to build a simple model driver, one that adds electrostatics (Coulombic interactions) to an existing Van Der Waals (Lennard Jones) model driver.

However, I cannot find a binding `KIM_COMPUTE_ARGUMENT_NAME_` that surfaces particle charge. Am I missing something or is this not a current capability?

**Comment by ellio167** [comment]
Hello,
Thanks for your question.  The KIM API is currently based on the idea of short-range particle interactions (there is an influence distance--allowing for the definition of a particle-energy function that can be computed with only a knowledge of the particle's "local environment").  This allows for a domain-decomposition approach to parallel computations where the KIM-API interatomic model needs no knowledge of the details of how the parallel computation is being achieved. Unfortunately, electrostatics does not fit this scheme and requires a knowledge of the entire system being simulated (and thus, needs many details about the parallel computing scheme being used by the simulator code).  Due to these complications, we have not (yet) been able to establish a standard way to describe electrostatics computations that can be embraced by the molecular modeling community.  So, the KIM-API does not currently have any support native for charge or electrostatics.

**Comment by adityakavalur** [comment]
Thanks for the reply!
While I agree with you on the electrostatics front, I would make a distinction for atomic-charge as it is solely particle dependent. I hope you consider providing a binding for it, so that users may locally implement a model-driver suitable for their needs even if its not acceptable for broader distribution through the OpenKIM web infrastructure. Although others may argue that it is a slippery slope.

Looking forward to see how you all approach this problem more holistically!

**Comment by ellio167** [comment]
Thanks for your comment.  FYI, there is an "Extension" mechanism in the KIM API that would definitely allow you to implement a special purpose model-driver that could work with a simulator which is aware of the extension.  The mechanism has not been exploited by users yet, and I'm afraid it is not documented very extensively.  If you would like to try this, I would be happy to provide some guidance/help.

**Comment by adityakavalur** [comment]
Thanks for the information! That sounds interesting, I will keep it in mind for any future usage.

For the current requirement I was able to find a workaround, I basically modified the [LJ model driver](https://openkim.org/id/LJ__MD_414112407348_003) to add the coulombic part and added a fixed charge for each i-i species line in the [model's](https://openkim.org/id/LJ_ElliottAkerson_2015_Universal__MO_959249795837_003) param file.
The catch is that the LAMMPS atomic-charge and OpenKIM species-charge are not aware of each other, so it needs a manual consistency check before usage. Additionally, each species can have only one charge state.

I am still testing it out, but I think it meets my initial requirements so I'm good for now.
